version: '3.8'

services:
  numerist:
    build: .
    container_name: numerist
    restart: unless-stopped
    ports:
      - "3332:3332"
    environment:
      - NODE_ENV=production
      - PORT=3332
      - HOST=0.0.0.0 